# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lR2IA1hE9sai_23pYbwFhfQPabTVNVQ
"""

#pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.2
#from gramformer import Gramformer
#!pip install spacy
#import spacy.cli
#spacy.cli.download("en_core_web_md")
#!pip install srsly
#!pip install -U git+https://github.com/PrithivirajDamodaran/Gramformer.git
#!pip install youtube_transcript_api

# Youtube Transcript Extractor Packages
from youtube_transcript_api import YouTubeTranscriptApi as yta

from youtube_transcript_api.formatters import Formatter
from youtube_transcript_api.formatters import JSONFormatter
from youtube_transcript_api.formatters import TextFormatter
from youtube_transcript_api.formatters import WebVTTFormatter
from youtube_transcript_api.formatters import SRTFormatter

# Language Correction Packages
from gramformer import Gramformer

# Deep Learning Packages
import torch

def set_seed(seed):
  torch.manual_seed(seed)
  if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

set_seed(1212)

# Get a transcript from a certain youtube video selected by ID
raw = yta.get_transcript('30IpveNICwU', languages=['en'])

text_formatter = TextFormatter()
text_formatted = text_formatter.format_transcript(raw)

print('[text_formatted]')
# print(text_formatted)
print('-' * 100)

gf = Gramformer(models = 1, use_gpu=False) # 1=corrector, 2=detector
text_corrected = gf.correct(text_formatted, max_candidates=1)

# print(type(text_corrected))

# text_splitted = text_corrected.splitlines()

# f = open('./result.txt', 'a')
# for i in range(0, len(text_splitted)):
#   f.write(text_splitted[i])
# f.close()

print('[text_corrected]')
print(text_corrected)
print('-' * 100)
