version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:15.5-bullseye
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastapi_lms
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sungminwoo.devops@gmail.com
      PGADMIN_DEFAULT_PASWORD: root
    ports:
      - "5050:80"
    networks:
      - postgres
    volumes: /var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: